#!/usr/bin/sh
create_link() {
  if [ ! -e "$2" ]; then
    ln -s "$1" "$2"
  fi
}

create_link ~/.dots/.xinitrc ~/.xinitrc
create_link ~/.dots/.zshrc ~/.zshrc
create_link ~/.dots/.gitconfig ~/.gitconfig

create_link ~/.dots/dwm ~/.config/dwm
create_link ~/.dots/st ~/.config/st
create_link ~/.dots/nvim ~/.config/nvim
create_link ~/.dots/tmux ~/.config/tmux
