#!/usr/bin/bash


# --------------
# PKG INSTALL
# --------------

# Update system
# --------------
sudo pacman -Syu
sudo pacman -S --needed --noconfirm $(cat packages)


# --------------
# BASIC CONFIG
# --------------
cd ~
mkdir dwl dox pix vid mnt opt bin rec

git clone https://github.com/ostadsog/rpo/dots ~/

# --------------
# SERVICES
# --------------
sudo systemctl enable pulseaudio


# -----------------
# BUILD DWM and ST
# -----------------
cd ~/dox/repo/rpo/dots/st
sudo make clean install

# --------------
# SYMLINKS
# --------------
ln -s --force ~/rpo/dots/nvim/ ~/.config/
ln -s --force ~/rpo/dots/tmux/ ~/.config/
ln -s --force ~/rpo/dots/dunst/ ~/.config/
ln -s --force ~/rpo/dots/qtile/ ~/.config/
ln -s --force ~/rpo/dots/.xinitrc ~/
ln -s --force ~/rpo/dots/.bashrc ~/
ln -s --force ~/rpo/dots/.gitconfig ~/

ln -s --force ~/rpo/dots/misc/mimeapps.list ~/.config/
ln -s --force ~/rpo/dots/misc/user-dirs.dirs  ~/.config/
ln -s --force ~/rpo/dots/misc/fontconfig/ ~/.config/
ln -s --force ~/rpo/dots/misc/gtk-3.0/ ~/.config/
ln -s --force ~/rpo/dots/misc/picom/ ~/.config/

ln -s --force ~/rpo/dots/bin/setbg ~/bin/
ln -s --force ~/rpo/dots/bin/shot ~/bin/
ln -s --force ~/rpo/dots/bin/tmuxer ~/bin/
ln -s --force ~/rpo/dots/bin/autostart ~/bin/
ln -s --force ~/rpo/dots/bin/launcher ~/bin/


sudo ln -s --force ~/rpo/dots/misc/Orchis-Dark/ /usr/share/themes/
