#! /usr/bin/sh

# Xorg
sudo xbps-install -y xorg-minimal xinit xauth xprop xrandr
    # Base utils
sudo xbps-install -y base-devel libX11-devel libXft-devel libXinerama-devel
    # Fonts
sudo xbps-install -y font-adobe-source-code-pro font-vazir font-awesome
    # Extra Fonts
sudo xbps-install -y noto-fonts-ttf noto-fonts-emoji noto-fonts-cjk
    # Audio
sudo xbps-install -y pulseaudio pulseaudio-utils pavucontrol
    # Xorg utils
sudo xbps-install -y xclip xset setxkbmap xinput xprop xrandr xdg-user-dirs xdg-utils 
    # Command Line tools
sudo xbps-install -y ffmpeg wget curl btop axel fd ripgrep fzf zoxide 
    # Dev
sudo xbps-install -y neovim luarocks tmux uv python git qtile dmenu python3-psutil
    # Apps
sudo xbps-install -y firefox pcmanfm sxiv zathura zathura-pdf-mupdf scrot
    # More apps
sudo xbps-install -y gimp vlc xf86-video-nouveau  papirus-icon-theme xwallpaper picom fastfetch

#
# # to install  lsp servers
# sudo xbps-install -y nodejs
#
# ### Basic Sys config
# sudo rm /var/service/agetty-tty{3,4,5,6}
#
# # Make home directories.
# cd
# mkdir dl dox vids pix 
# mkdir ~/.local/bin
#
# mkdir dox/repos
# mkdir dox/ebooks
#
# # Clone dotfiles
# git clone https://github.com/ostadsgo/dots
# mv dots ~/dox/repos/
#
# cd ..
# cd st
# sudo make clean install


# # Link to important configs
# ln -s --force ~/dox/repo/dots/qtile ~/.config/qtile
# ln -s --force ~/dox/repo/dots/nvim ~/.config/nvim
# ln -s --force ~/dox/repo/dots/tmux ~/.config/tmux
# ln -s --force ~/dox/repo/dots/picom ~/.config/picom
# ln -s --force ~/dox/repo/dots/.xinitrc ~/.xinitrc
# ln -s --force ~/dox/repo/dots/.bashrc ~/.bashrc
#
# # Git config
# ln -s --force ~/dox/repo/dots/misc/.gitconfig ~/.gitconfig
#
# # App Config
# ln -s --force ~/dox/repo/dots/misc/mimeapps.list ~/.config/mimeapps.list
# ln -s --force ~/dox/repo/dots/misc/user-dirs.dirs  ~/.config/user-dirs.dirs
# ln -s --force ~/dox/repo/dots/misc/fontconfig/ ~/.config/fontconfig
# ln -s --force ~/dox/repo/dots/misc/gtk-3.0/ ~/.config/gtk-3.0
#
# # Scripts
# ln -s --force ~/dox/repo/dots/bin/tmuxer  ~/.local/bin
# ln -s --force ~/dox/repo/dots/bin/launcher  ~/.local/bin
# ln -s --force ~/dox/repo/dots/bin/setbg ~/.local/bin
# ln -s --force ~/dox/repo/dots/bin/autostart.sh  ~/.local/bin/
#
# # Resources config
# ln -s --force ~/dox/repo/dots/.Xresources ~/.Xresources
#
# # GTK
# sudo ln -s --force ~/dox/repo/dots/misc/Orchis-Dark/ /usr/share/themes

