#! /usr/bin/bash

# General
export HOME=~
export EDITOR="nvim"
export BROWSER="chrome"
export TERMINAL="alacritty"
export ZDOTDIR=$HOME/.config/zsh

path+=$HOME/.local/bin/scripts


# Starting X
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
