require("modules/options")
require("modules/keymaps")
require("modules/plugins")
require("modules/colorscheme")
-- require("modules/lualine")
require("modules/comment")
require("modules/treesitter")
require("modules/telescope")
require("modules/cmp")
require("modules/mason")
require("modules/lspconf")
require("modules/nulls")
